# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(376, 639)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStatusTip("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.exeLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.exeLineEdit.setObjectName("exeLineEdit")
        self.horizontalLayout.addWidget(self.exeLineEdit)
        self.exePathButton = QtWidgets.QPushButton(self.centralwidget)
        self.exePathButton.setObjectName("exePathButton")
        self.horizontalLayout.addWidget(self.exePathButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.resLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resLineEdit.sizePolicy().hasHeightForWidth())
        self.resLineEdit.setSizePolicy(sizePolicy)
        self.resLineEdit.setMaximumSize(QtCore.QSize(16777215, 23))
        self.resLineEdit.setObjectName("resLineEdit")
        self.horizontalLayout_2.addWidget(self.resLineEdit)
        self.resPathButton = QtWidgets.QPushButton(self.centralwidget)
        self.resPathButton.setObjectName("resPathButton")
        self.horizontalLayout_2.addWidget(self.resPathButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.loadButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadButton.setObjectName("loadButton")
        self.verticalLayout_2.addWidget(self.loadButton)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setMinimumSize(QtCore.QSize(0, 0))
        self.tableView.setStyleSheet("QTableView QScrollBar::vertical{ /*主体部分*/\n"
"    width:10px;\n"
"    background:rgb(89,89,89);\n"
"    border:none;\n"
"    border-radius:5px;\n"
"}\n"
"QTableView QScrollBar::handle::vertical{ /*滑块主体*/\n"
"    border-radius:5px;\n"
"    width: 10px;\n"
"    background:rgb(173,173,173);\n"
"}\n"
"QTableView QScrollBar::handle::vertical::hover{\n"
"    background:rgb(232,232,232);\n"
"}\n"
"QTableView QScrollBar::add-line::vertical{/*上箭头*/\n"
"    border:none;\n"
"}\n"
"QTableView QScrollBar::sub-line::vertical{/*下箭头*/\n"
"    border:none;\n"
"}\n"
"\n"
"\n"
"\n"
"QTableView\n"
"{\n"
"    background: rgb(55,55,55);\n"
"}\n"
"QTableView{\n"
"    selection-background-color:rgb(255,0,0);\n"
"    background-color:rgb(50,50,50);\n"
"    border:1px solid rgb(70,70,70);\n"
"    color:rgb(200,200,200)\n"
"}\n"
" \n"
"QTableView::item\n"
"{\n"
"       border:1px solid rgb(65,65,65);\n"
"    color:rgb(200,200,200);\n"
" \n"
"}\n"
"QTableView::item:hover\n"
"{\n"
"    background-color: rgb(30,30,30);\n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color:rgb(31,163,246);\n"
"}\n"
"QTableView::item::selected\n"
"{\n"
"    background-color: rgb(30,30,30);\n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color:rgb(31,163,246);\n"
"}\n"
" \n"
" \n"
" \n"
" \n"
"QHeaderView::section{\n"
"    background-color:rgb(90,90,90);\n"
"      color:rgb(200,200,200);\n"
"    border:1px solid rgb(60,60,60);\n"
"    border-bottom:1px solid rgb(70,70,70);\n"
"    height:27px;\n"
"    min-width:38px;\n"
"}\n"
"QHeaderView::section:hover\n"
"{\n"
"    background-color:rgb(80,80,80);\n"
" \n"
"}")
        self.tableView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.tableView)
        self.runButton = QtWidgets.QPushButton(self.centralwidget)
        self.runButton.setObjectName("runButton")
        self.verticalLayout_2.addWidget(self.runButton)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "网页自动注册1.0"))
        self.exePathButton.setText(_translate("MainWindow", "配置环境"))
        self.resPathButton.setText(_translate("MainWindow", "选择资源"))
        self.loadButton.setText(_translate("MainWindow", "解析资源文件"))
        self.runButton.setText(_translate("MainWindow", "启动网页自动注册系统"))
import icon
